issuer: http://dex-entra-telemark-alt:5556/dex
storage:
    type: sqlite3
    config:
        file: /tmp/dex-telemark.db

web:
    http: 0.0.0.0:5556

oauth2:
    skipApprovalScreen: true

staticClients:
    -   id: test-app-alt
        name: Keycloak broker (external â†’ entra-telemark-alt)
        secret: test-secret
        redirectURIs:
            - http://keycloak:8080/realms/external/broker/entra-telemark-alt/endpoint
            - http://localhost:8890/realms/external/broker/entra-telemark-alt/endpoint

enablePasswordDB: true
staticPasswords:
    -   email: alice.basic@telemark-alt.no
        username: alice.basic@telemark-alt.no
        userID: 11111111-1111-1111-1111-111111111111
        hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK # password = password
    -   email: jon.basic@telemark-alt.no
        username: jon.basic@telemark-alt.no
        userID: 22222222-2222-2222-2222-222222222222
        hash: $2b$10$pECRn7RvUKar9qQjpPUvGO8ZNuK5xezvXZOnX6TaD.SddrZwsMZBK # password = password
