detectSchema: true
detectResourceTypes: true

users:
    enabled: true
    operations:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    sortAttributes:
        - userName

    post_tests:
        -   request:
              {
                  "schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User" ],
                  "externalId": "11111111-1111-1111-1111-111111111111",
                  "userName": "alice.basic@rogaland.no",
                  "active": true,
                  "name": { "givenName": "Alice", "familyName": "Basic" },
                  "emails":
                    [ { "value": "alice.basic@rogaland.no", "primary": true } ],
                  "roles": [ { "value": "read" } ],
              }
            response:
              {
                  "type": "object",
                  "properties":
                    {
                        "schemas":
                          {
                              "type": "array",
                              "items": { "type": "string" },
                              "contains":
                                {
                                    "const": "urn:ietf:params:scim:schemas:core:2.0:User",
                                },
                          },
                        "id": { "type": "string" },
                        "meta": { "type": "object" },
                        "urn:ietf:params:scim:schemas:core:2.0:User":
                          {
                              "type": "object",
                              "properties":
                                {
                                    "userName":
                                      {
                                          "type": "string",
                                          "const": "alice.basic@rogaland.no",
                                      },
                                    "emails":
                                      {
                                          "type": "array",
                                          "items":
                                            {
                                                "type": "object",
                                                "properties":
                                                  {
                                                      "value":
                                                        {
                                                            "type": "string",
                                                            "const": "alice.basic@rogaland.no",
                                                        },
                                                  },
                                            },
                                      },
                                },
                              "required": [ "userName" ],
                              "additionalProperties": true,
                          },
                    },
                  "required":
                    [
                        "schemas",
                        "id",
                        "urn:ietf:params:scim:schemas:core:2.0:User",
                    ],
                  "additionalProperties": true,
              }

    filter_tests:
        -   filter: userName eq "alice.basic@rogaland.no"
            user_schema:
              {
                  "type": "object",
                  "properties":
                    {
                        "schemas":
                          {
                              "type": "array",
                              "items": { "type": "string" },
                              "contains":
                                {
                                    "const": "urn:ietf:params:scim:schemas:core:2.0:User",
                                },
                          },
                        "urn:ietf:params:scim:schemas:core:2.0:User":
                          {
                              "type": "object",
                              "properties":
                                {
                                    "userName":
                                      {
                                          "type": "string",
                                          "const": "alice.basic@rogaland.no",
                                      },
                                },
                              "required": [ "userName" ],
                              "additionalProperties": true,
                          },
                    },
                  "required":
                    [ "schemas", "urn:ietf:params:scim:schemas:core:2.0:User" ],
                  "additionalProperties": true,
              }

    put_tests:
        -   id: AUTO
            request:
              {
                  "schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User" ],
                  "externalId": "11111111-1111-1111-1111-111111111111",
                  "userName": "alice.basic@rogaland.no",
                  "active": true,
                  "name": { "givenName": "Alice2", "familyName": "Basic2" },
                  "emails":
                    [ { "value": "alice.basic@rogaland.no", "primary": true } ],
                  "roles": [ { "value": "test" } ],
              }
            response:
              {
                  "type": "object",
                  "properties":
                    {
                        "schemas":
                          {
                              "type": "array",
                              "items": { "type": "string" },
                              "contains":
                                {
                                    "const": "urn:ietf:params:scim:schemas:core:2.0:User",
                                },
                          },
                        "id": { "type": "string" },
                        "meta": { "type": "object" },
                        "urn:ietf:params:scim:schemas:core:2.0:User":
                          {
                              "type": "object",
                              "properties":
                                {
                                    "userName":
                                      {
                                          "type": "string",
                                          "const": "alice.basic@rogaland.no",
                                      },
                                    "name":
                                      {
                                          "type": "object",
                                          "properties":
                                            {
                                                "givenName":
                                                  {
                                                      "type": "string",
                                                      "const": "Alice2",
                                                  },
                                                "familyName":
                                                  {
                                                      "type": "string",
                                                      "const": "Basic2",
                                                  },
                                            },
                                      },
                                    "emails":
                                      {
                                          "type": "array",
                                          "items":
                                            {
                                                "type": "object",
                                                "properties":
                                                  {
                                                      "value":
                                                        {
                                                            "type": "string",
                                                            "const": "alice.basic@rogaland.no",
                                                        },
                                                  },
                                            },
                                      },
                                },
                              "required": [ "userName" ],
                              "additionalProperties": true,
                          },
                    },
                  "required":
                    [
                        "schemas",
                        "id",
                        "urn:ietf:params:scim:schemas:core:2.0:User",
                    ],
                  "additionalProperties": true,
              }

    patch_tests:
        -   id: AUTO
            request:
              {
                  "schemas": [ "urn:ietf:params:scim:api:messages:2.0:PatchOp" ],
                  "Operations":
                    [
                        {
                            "op": "replace",
                            "path": "name.familyName",
                            "value": "alice2",
                        },
                    ],
              }
            response:
              {
                  "type": "object",
                  "properties":
                    {
                        "schemas":
                          {
                              "type": "array",
                              "items": { "type": "string" },
                              "contains":
                                {
                                    "const": "urn:ietf:params:scim:schemas:core:2.0:User",
                                },
                          },
                        "id": { "type": "string" },
                        "meta": { "type": "object" },
                        "urn:ietf:params:scim:schemas:core:2.0:User":
                          {
                              "type": "object",
                              "properties":
                                {
                                    "name":
                                      {
                                          "type": "object",
                                          "properties":
                                            {
                                                "familyName":
                                                  {
                                                      "type": "string",
                                                      "const": "alice2",
                                                  },
                                            },
                                      },
                                },
                              "required": [ "name" ],
                              "additionalProperties": true,
                          },
                    },
                  "required":
                    [
                        "schemas",
                        "id",
                        "urn:ietf:params:scim:schemas:core:2.0:User",
                    ],
                  "additionalProperties": true,
              }

    delete_tests:
        -   id: AUTO
